version: "{branch} #{build}"

shallow_clone: true

image:
    #- Visual Studio 2019
    - Visual Studio 2017
    - Visual Studio 2015

environment:
    matrix:
        # VS 2019 and newer are tested with Azure Pipelines
        #- generator: "Visual Studio 16 2019"
        - generator: "Visual Studio 15 2017"
        - generator: "Visual Studio 14 2015"
        - generator: "Visual Studio 12 2013"
        - generator: "Visual Studio 11 2012"
        - generator: "Visual Studio 10 2010"

configuration:
    - Debug
    #- Release

platform:
    - Win32
    - x64

matrix:
    fast_finish: false
    exclude:
        - image:      Visual Studio 2017
          generator: "Visual Studio 12 2013"
        - image:      Visual Studio 2017
          generator: "Visual Studio 11 2012"
        - image:      Visual Studio 2017
          generator: "Visual Studio 10 2010"
        - image:      Visual Studio 2015
          generator: "Visual Studio 15 2017"
        - image:      Visual Studio 2015
          generator: "Visual Studio 14 2015"

before_build:
    - mkdir build && cd build
    - cmake -A %platform% -G "%generator%" -DGSL_LITE_OPT_BUILD_TESTS=ON -DGSL_LITE_OPT_BUILD_EXAMPLES=ON ..

build_script:
    - cmake --build . --config %configuration%

test_script:
    - ctest --output-on-failure -C %configuration%
